spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vpp_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # use 'validate', 'create', 'create-drop', or 'none' as needed
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect